name: kut_in
description: A Flutter app that shows random, wise Kanye West quotes.
version: 1.1.1
author: Bapusaheb Patil <hi@bapspatil.com>
homepage: https://github.com/bapspatil/kut_in

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  url_launcher: ^5.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app_icon.png"
  image_path_ios: "assets/app_icon_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bapspatil.png

  fonts:
    - family: Imperator
      fonts:
        - asset: assets/fonts/ImperatorBold.ttf