name: kut_in
description: A Flutter app that shows random, wise Kanye West quotes.
version: 1.0.0
author: Bapusaheb Patil <hi@bapspatil.com>
homepage: https://github.com/bapspatil/kut_in

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Imperator
      fonts:
        - asset: fonts/ImperatorBold.ttf